properties:
  beer_sensor:
    type: sensor
    label: Sensor de Fermentador
    description: Sonda na cerveja para medir a temperatura do fermentador
  fridge_sensor:
    type: sensor
    label: Sensor da Câmara
    description: Sonda na câmara ou geladeira de fermentação
  heater:
    type: actor
    label: Aquecedor
    description: Atuador para o aquecimento
  cooler:
    type: actor
    label: Resfriador
    description: Atuador para o resfriamento
  target:
    type: number
    label: Setpoint de Fermentação (°C)
    description: Temperatura alvo desejada para a cerveja
    default: 20
  kp:
    type: number
    label: Kp (Proporcional)
    default: 10.0
  ki:
    type: number
    label: Ki (Integral)
    default: 0.0
  kd:
    type: number
    label: Kd (Derivativo)
    default: 80.0
  cycle_time:
    type: number
    label: Ciclo do Controle (segundos)
    default: 60
  min_on_time:
    type: number
    label: Tempo Mínimo Ligado (segundos)
    default: 180
  min_off_time:
    type: number
    label: Tempo Mínimo Desligado (segundos)
    default: 300
  dead_time:
    type: number
    label: Dead Time entre Ligações (segundos)
    default: 300
  freeze_protect_temp:
    type: number
    label: Limite de Proteção Anti-Congelamento (°C)
    description: Temperatura mínima segura para evitar congelar a cerveja
    default: 1.0
